runs:
  using: "composite"
  steps:
    - name: Install AWS CLI and serverless
      shell: bash
      run: |
        apt-get update && apt-get install -y python3-venv python3-pip
        pip3 install awscli botocore==1.29.20
        yarn global add serverless

    - name: Configure AWS credentials
      shell: bash
      run: | 
        mkdir -p $HOME/.aws && echo "[default]" > $HOME/.aws/credentials
        echo "[default]" > $HOME/.aws/credentials
        echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> $HOME/.aws/credentials
        echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> $HOME/.aws/credentials
        chmod 600 $HOME/.aws/credentials