name: Test Pull Request

env:
  BUCKET_NAME: 'franchise-github-action-pullrequest'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

on:
  workflow_dispatch:

  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-config

      - name: S3 pull config
        uses: ./.github/actions/s3-pull-config

      - name: Install project dependencies
        run: yarn install

      - name: Build and Deploy
        run: |
          yarn lint
          yarn build --filter=!./apps/web ${EXTRA_COMMANDS} --concurrency=1
          yarn deploy

      - name: S3 push config
        uses: ./.github/actions/s3-push-config

      - name: Clean up
        run: |
          rm -rf ./node_modules/.cache/turbo
